---
name: automerge
on:
  push:
    branches:
      - update/**
jobs:
  check-mergeability:
    if: ${{ github.actor == 'NikitaSkrynnik' }}
    uses: networkservicemesh/.github/.github/workflows/check-mergeability.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    needs: [check-mergeability]
    uses: networkservicemesh/.github/.github/workflows/automerge.yaml@main

  resolve_conflicts:
    needs: [check-mergeability]
    if: ${{ always() && needs.check-mergeability.result == 'failure' }}
    uses: networkservicemesh/.github/.github/workflows/resolve-conflicts.yaml@main
    with:
      pr_branch_ref: ${{ needs.check-mergeability.outputs.pr_branch_ref }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
